apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ClubCedille/k8s-common
    path: common
    targetRevision: HEAD